### ISSUE TITLE
Remove "Install from Github" from Readme

### ISSUE THREAD

**Issue by cutterkom** [TS404/WikidataR#11]
Hey, 
I accidentally added a "Install from Github" part in my pull request that you accepted. Please remove it, because it leads to a wrong package (my fork instead of **this** version). 

Thank you!

**Comment by hugolpz** [comment]
@TS404  @cutterkom @metacoretechs hello,

Could you review this PR and, if necessary, grand adminship to @cutterkom . As WikidataR move to open source model and reduced coding intensity, it is important to multiply github administrators so the project stays resilient and reactive to PR.

**Comment by TS404** [comment]
done!
