### ISSUE TITLE
Add tags to repository

### ISSUE THREAD

**Issue by hugolpz** [TS404/WikidataR#13]
[r](https://github.com/topics/r) [wikidata](https://github.com/topics/wikidata) [api-client](https://github.com/topics/api-client)

**Comment by hugolpz** [comment]
Like this : 
![image](https://github.com/TS404/WikidataR/assets/1420189/1ebb3eef-6172-454d-a3ad-4d37799c8a78)

**Comment by TS404** [comment]
done!

**Comment by TS404** [comment]
done!
